openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Sample API'
  description: Initial example to submit Elasticsearch queries

paths:
  /search:
    get:
      summary: 'Submits a query to Elasticsearch'
      operationId: search
      tags:
        - search
      parameters:
        - name: query
          in: query
          description: Query to be submitted
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/ResultList'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ResultList:
      type: object
      properties:
        total_hits:
          type: integer
        total_pages:
          type: integer
        suggestion:
          type: string
        search_time:
          type: integer
        results:
          type: array
          items:
            $ref: '#/components/schemas/Result'
    Result:
      type: object
      properties:
        title:
          type: string
        url:
          type: string
        abs:
          type: string
        reading_time:
          type: integer
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string