server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gquery.development@gmail.com
    password: jlzx kgvu owki onvl
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
